spring:
  datasource:
    url: jdbc:sqlserver://fundraiserserver.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: fundraiser
    password: password@123
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
#      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9191
