spring:
  datasource:
    url: jdbc:sqlserver://fundraiserserver.database.windows.net:1433;databaseName=fundRaiserDB;DBencrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: fundraiser
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: updateq
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9092
